{{
	config(
		materialized="table" ,
		alias="dim_dates" ,
		schema="dev" ,
		unique_key="DATE_ID"
	)
}}

SELECT TO_CHAR(DATUM, 'yyyymmdd')::INT AS DATE_ID,
       DATUM AS DATE_ACTUAL,
       EXTRACT(EPOCH FROM DATUM) AS EPOCH,
       TO_CHAR(DATUM, 'fmDDth') AS DAY_SUFFIX,
       TO_CHAR(DATUM, 'TMDay') AS DAY_NAME,
       EXTRACT(ISODOW FROM DATUM) AS DAY_OF_WEEK,
       EXTRACT(DAY FROM DATUM) AS DAY_OF_MONTH,
       DATUM - DATE_TRUNC('quarter', DATUM)::DATE + 1 AS DAY_OF_QUARTER,
       EXTRACT(DOY FROM DATUM) AS DAY_OF_YEAR,
       TO_CHAR(DATUM, 'W')::INT AS WEEK_OF_MONTH,
       EXTRACT(WEEK FROM DATUM) AS WEEK_OF_YEAR,
       EXTRACT(ISOYEAR FROM DATUM) || TO_CHAR(DATUM, '"-W"IW-') || EXTRACT(ISODOW FROM DATUM) AS WEEK_OF_YEAR_ISO,
       EXTRACT(MONTH FROM DATUM) AS MONTH_ACTUAL,
       TO_CHAR(DATUM, 'TMMonth') AS MONTH_NAME,
       TO_CHAR(DATUM, 'Mon') AS MONTH_NAME_ABBREVIATED,
       EXTRACT(QUARTER FROM DATUM) AS QUARTER_ACTUAL,
       CASE
           WHEN EXTRACT(QUARTER FROM DATUM) = 1 THEN 'First'
           WHEN EXTRACT(QUARTER FROM DATUM) = 2 THEN 'Second'
           WHEN EXTRACT(QUARTER FROM DATUM) = 3 THEN 'Third'
           WHEN EXTRACT(QUARTER FROM DATUM) = 4 THEN 'Fourth'
           END AS QUARTER_NAME,
       EXTRACT(YEAR FROM DATUM) AS year_actual,
       DATUM + (1 - EXTRACT(ISODOW FROM DATUM))::INT AS FIRST_DAY_OF_WEEK,
       DATUM + (7 - EXTRACT(ISODOW FROM DATUM))::INT AS LAST_DAY_OF_WEEK,
       DATUM + (1 - EXTRACT(DAY FROM DATUM))::INT AS FIRST_DAY_OF_MONTH,
       (DATE_TRUNC('MONTH', DATUM) + INTERVAL '1 MONTH - 1 day')::DATE AS LAST_DAY_OF_MONTH,
       DATE_TRUNC('quarter', DATUM)::DATE AS FIRST_DAY_OF_QUARTER,
       (DATE_TRUNC('quarter', DATUM) + INTERVAL '3 MONTH - 1 day')::DATE AS LAST_DAY_OF_QUARTER,
       TO_DATE(EXTRACT(YEAR FROM DATUM) || '-01-01', 'YYYY-MM-DD') AS FIRST_DAY_OF_YEAR,
       TO_DATE(EXTRACT(YEAR FROM DATUM) || '-12-31', 'YYYY-MM-DD') AS LAST_DAY_OF_YEAR,
       TO_CHAR(DATUM, 'mmyyyy') AS MMYYYY,
       TO_CHAR(DATUM, 'mmddyyyy') AS MMDDYYYY,
       CASE
           WHEN EXTRACT(ISODOW FROM DATUM) IN (6, 7) THEN TRUE
           ELSE FALSE
           END AS WEEKEND_INDR
FROM (SELECT '1970-01-01'::DATE + SEQUENCE.DAY AS DATUM
      FROM GENERATE_SERIES(0, 29219) AS SEQUENCE (DAY)
      GROUP BY SEQUENCE.DAY) DQ
ORDER BY 1